# Welcome to Jekyll!
# This config file is meant for settings that affect your whole blog.

# Site settings
title: CortexEdu
email: your-email@example.com
description: >- 
  Your one-stop resource for coding education. Learn to code and enhance your skills!
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://geekygalileo.github.io" # the base hostname & protocol for your site

# Social media settings
twitter_username: jekyllrb
github_username: geekygalileo

# Build settings
theme: minima # Specify your theme here
plugins:
  - jekyll-feed

# Exclude certain files from processing
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Other optional settings
markdown: kramdown # Choose a markdown engine

